"use client";
import Head from "next/head";
import ControlPanelModal from "@/components/ControlPanelModal/control_panel";
import TopNavbar from "@/components/TopNavbar/TopNavBar";
import ScrollToTop from "@/components/shared/ScrollToTop";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
// import Sidebar from "@/components/LeftSidebar/SubMenu";
import { useState } from "react";

import Sidebar from "@/components/LeftSidebar/LeftSideBar";
import { usePathname, useRouter, useSearchParams } from "next/navigation";

// import SidebarTest from "@/components/sidebar/Sidebar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Lawfirm Dashboard",
//   description: "Generated by Clickers",
// };

export default function ClientLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [active, setActive] = useState(false);

  const toggleActive = () => {
    setActive(!active);
  };
  const router = usePathname();

  const isLoginPage = router.startsWith("/login");

  return (
    <html lang="en">
      <Head>
        <title>Dashboard</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      {isLoginPage ? (
        <body className={inter.className}>{children}</body>
      ) : (
        <body className={inter.className}>
          <div className={`main-wrapper-content ${active && "active"}`}>
            <>
              <TopNavbar toogleActive={toggleActive} />
              <Sidebar toggleActive={toggleActive} />
            </>

            {children}
          </div>
          {/* </div> */}

          {/* ScrollToTop */}

          <>
            <ScrollToTop />

            <ControlPanelModal />
          </>
        </body>
      )}
    </html>
  );
}
