
import Head from "next/head";
import { Inter } from "next/font/google";
import { Locale, i18n } from '../../i18n.config';

import theme from "../styles/theme";
import "react-tabs/style/react-tabs.css";
import ClientLayout from "./client.layout";
import { Metadata } from "next";
import ControlPanelModal from "../components/ControlPanelModal/control_panel";
import Providers from "../components/providers";

export const metadata: Metadata = {
  title: "Lawfirm Dashboard",
  description: "Generated by Clickers",
};
export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}


export default function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: Locale } }) {

  return (

    <html lang={params.lang}>
          <Head>
        <title>Dashboard</title>
        {/* <link rel="preload" href="style.css" as="style" /> */}
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
        
      <Providers>

          <ClientLayout children={children} />


      </Providers>
      
      </html>
  );
}
